name: build
on:
  push:
    paths:
      - "*.gradle"
      - "gradle.properties"
      - "src/**"
      - "./github/**"
      - "datapack/**"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --stacktrace

      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/libs/**
